// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:recette/models/recipe.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(RecipeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(RecipeAdapter());
  }
}
